// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onWakeup(lv_event_t *e);
void onMenuClick(lv_event_t *e);
void onNextProfile(lv_event_t *e);
void onPreviousProfile(lv_event_t *e);
void onProfileScreenLoad(lv_event_t *e);
void onProfileLoad(lv_event_t *e);
void onMenuScreenLoad(lv_event_t *e);
void onStandby(lv_event_t *e);
void onBrewScreen(lv_event_t *e);
void onSteamScreen(lv_event_t *e);
void onWaterScreen(lv_event_t *e);
void onGrindScreen(lv_event_t *e);
void onBrewScreenLoad(lv_event_t *e);
void onBrewStart(lv_event_t *e);
void onFlush(lv_event_t *e);
void onVolumetricClick(lv_event_t *e);
void onVolumetricHold(lv_event_t *e);
void onProfileSelect(lv_event_t *e);
void onProfileSettings(lv_event_t *e);
void onBrewTempLower(lv_event_t *e);
void onBrewTempRaise(lv_event_t *e);
void onBrewTimeRaise(lv_event_t *e);
void onBrewTimeLower(lv_event_t *e);
void onVolumetricDelete(lv_event_t *e);
void onProfileSave(lv_event_t *e);
void onProfileAccept(lv_event_t *e);
void onProfileSaveAsNew(lv_event_t *e);
void onSimpleProcessScreenLoad(lv_event_t *e);
void onSimpleProcessToggle(lv_event_t *e);
void onSteamTempLower(lv_event_t *e);
void onSteamTempRaise(lv_event_t *e);
void onStatusScreenLoad(lv_event_t *e);
void onBrewCancel(lv_event_t *e);
void onGrindScreenLoad(lv_event_t *e);
void onGrindToggle(lv_event_t *e);
void onGrindTimeRaise(lv_event_t *e);
void onGrindTimeLower(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
