// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

lv_obj_t *uic_BrewScreen_dials_tempText;
lv_obj_t *uic_BrewScreen_dials_pressureText;
lv_obj_t *uic_BrewScreen_dials_pressureTarget;
lv_obj_t *uic_BrewScreen_dials_pressureGauge;
lv_obj_t *uic_BrewScreen_dials_tempTarget;
lv_obj_t *uic_BrewScreen_dials_tempGauge;
lv_obj_t *ui_BrewScreen = NULL;
lv_obj_t *ui_BrewScreen_dials = NULL;
lv_obj_t *ui_BrewScreen_ImgButton5 = NULL;
lv_obj_t *ui_BrewScreen_contentPanel4 = NULL;
lv_obj_t *ui_BrewScreen_mainLabel3 = NULL;
lv_obj_t *ui_BrewScreen_startButton = NULL;
lv_obj_t *ui_BrewScreen_controlContainer = NULL;
lv_obj_t *ui_BrewScreen_modeSwitch = NULL;
lv_obj_t *ui_BrewScreen_volumetricButton = NULL;
lv_obj_t *ui_BrewScreen_weightLabel = NULL;
lv_obj_t *ui_BrewScreen_profileInfo = NULL;
lv_obj_t *ui_BrewScreen_Label1 = NULL;
lv_obj_t *ui_BrewScreen_Container3 = NULL;
lv_obj_t *ui_BrewScreen_profileSelectBtn = NULL;
lv_obj_t *ui_BrewScreen_profileName = NULL;
lv_obj_t *ui_BrewScreen_settingsButton = NULL;
lv_obj_t *ui_BrewScreen_adjustments = NULL;
lv_obj_t *ui_BrewScreen_tempContainer = NULL;
lv_obj_t *ui_BrewScreen_targetTemp = NULL;
lv_obj_t *ui_BrewScreen_downTempButton = NULL;
lv_obj_t *ui_BrewScreen_upTempButton = NULL;
lv_obj_t *ui_BrewScreen_Image5 = NULL;
lv_obj_t *ui_BrewScreen_targetContainer = NULL;
lv_obj_t *ui_BrewScreen_targetDuration = NULL;
lv_obj_t *ui_BrewScreen_upDurationButton = NULL;
lv_obj_t *ui_BrewScreen_downDurationButton = NULL;
lv_obj_t *ui_BrewScreen_Image4 = NULL;
lv_obj_t *ui_BrewScreen_byTimeButton = NULL;
lv_obj_t *ui_BrewScreen_saveButton = NULL;
lv_obj_t *ui_BrewScreen_acceptButton = NULL;
lv_obj_t *ui_BrewScreen_saveAsNewButton = NULL;
// event funtions
void ui_event_BrewScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        onMenuClick(e);
    }
    if (event_code == LV_EVENT_SCREEN_LOADED) {
        onBrewScreenLoad(e);
    }
}

void ui_event_BrewScreen_ImgButton5(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onMenuClick(e);
    }
}

void ui_event_BrewScreen_startButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewStart(e);
    }
    if (event_code == LV_EVENT_LONG_PRESSED) {
        onFlush(e);
    }
}

void ui_event_BrewScreen_modeSwitch(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onVolumetricClick(e);
    }
    if (event_code == LV_EVENT_LONG_PRESSED) {
        onVolumetricHold(e);
    }
}

void ui_event_BrewScreen_profileSelectBtn(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onProfileSelect(e);
    }
}

void ui_event_BrewScreen_settingsButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onProfileSettings(e);
    }
}

void ui_event_BrewScreen_downTempButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewTempLower(e);
    }
}

void ui_event_BrewScreen_upTempButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewTempRaise(e);
    }
}

void ui_event_BrewScreen_upDurationButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewTimeRaise(e);
    }
}

void ui_event_BrewScreen_downDurationButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onBrewTimeLower(e);
    }
}

void ui_event_BrewScreen_byTimeButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onVolumetricDelete(e);
    }
}

void ui_event_BrewScreen_saveButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onProfileSave(e);
    }
}

void ui_event_BrewScreen_acceptButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onProfileAccept(e);
    }
}

void ui_event_BrewScreen_saveAsNewButton(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onProfileSaveAsNew(e);
    }
}

// build funtions

void ui_BrewScreen_screen_init(void) {
    ui_BrewScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BrewScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_event_cb(ui_BrewScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_BrewScreen_screen_destroy);
    ui_object_set_themeable_style_property(ui_BrewScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_BrewScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Dark);

    ui_BrewScreen_dials = ui_dials_create(ui_BrewScreen);
    lv_obj_set_x(ui_BrewScreen_dials, 0);
    lv_obj_set_y(ui_BrewScreen_dials, 0);

    ui_BrewScreen_ImgButton5 = lv_imgbtn_create(ui_BrewScreen);
    lv_imgbtn_set_src(ui_BrewScreen_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_295763949, NULL);
    lv_obj_set_width(ui_BrewScreen_ImgButton5, 40);
    lv_obj_set_height(ui_BrewScreen_ImgButton5, 40);
    lv_obj_set_x(ui_BrewScreen_ImgButton5, 0);
    lv_obj_set_y(ui_BrewScreen_ImgButton5, 210);
    lv_obj_set_align(ui_BrewScreen_ImgButton5, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_ImgButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_ImgButton5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_contentPanel4 = lv_obj_create(ui_BrewScreen);
    lv_obj_set_width(ui_BrewScreen_contentPanel4, 360);
    lv_obj_set_height(ui_BrewScreen_contentPanel4, 360);
    lv_obj_set_align(ui_BrewScreen_contentPanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrewScreen_contentPanel4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_BrewScreen_contentPanel4, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrewScreen_contentPanel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrewScreen_contentPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_BrewScreen_contentPanel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_contentPanel4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_border_width(ui_BrewScreen_contentPanel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_mainLabel3 = lv_label_create(ui_BrewScreen_contentPanel4);
    lv_obj_set_width(ui_BrewScreen_mainLabel3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_BrewScreen_mainLabel3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_BrewScreen_mainLabel3, 0);
    lv_obj_set_y(ui_BrewScreen_mainLabel3, -140);
    lv_obj_set_align(ui_BrewScreen_mainLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_mainLabel3, "Brew");
    ui_object_set_themeable_style_property(ui_BrewScreen_mainLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_mainLabel3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_BrewScreen_mainLabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_startButton = lv_imgbtn_create(ui_BrewScreen_contentPanel4);
    lv_imgbtn_set_src(ui_BrewScreen_startButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_445946954, NULL);
    lv_obj_set_width(ui_BrewScreen_startButton, 40);
    lv_obj_set_height(ui_BrewScreen_startButton, 40);
    lv_obj_set_x(ui_BrewScreen_startButton, 0);
    lv_obj_set_y(ui_BrewScreen_startButton, 130);
    lv_obj_set_align(ui_BrewScreen_startButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_startButton, LV_OBJ_FLAG_HIDDEN); /// Flags
    ui_object_set_themeable_style_property(ui_BrewScreen_startButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_startButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_controlContainer = lv_obj_create(ui_BrewScreen_contentPanel4);
    lv_obj_remove_style_all(ui_BrewScreen_controlContainer);
    lv_obj_set_width(ui_BrewScreen_controlContainer, 360);
    lv_obj_set_height(ui_BrewScreen_controlContainer, 196);
    lv_obj_set_x(ui_BrewScreen_controlContainer, 0);
    lv_obj_set_y(ui_BrewScreen_controlContainer, -10);
    lv_obj_set_align(ui_BrewScreen_controlContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrewScreen_controlContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BrewScreen_controlContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrewScreen_controlContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_pad_row(ui_BrewScreen_controlContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrewScreen_controlContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_modeSwitch = lv_obj_create(ui_BrewScreen_controlContainer);
    lv_obj_set_width(ui_BrewScreen_modeSwitch, 160);
    lv_obj_set_height(ui_BrewScreen_modeSwitch, 50);
    lv_obj_set_align(ui_BrewScreen_modeSwitch, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrewScreen_modeSwitch, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BrewScreen_modeSwitch, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_modeSwitch, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_BrewScreen_modeSwitch, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    ui_object_set_themeable_style_property(ui_BrewScreen_modeSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_BrewScreen_modeSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_border_width(ui_BrewScreen_modeSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_volumetricButton = lv_img_create(ui_BrewScreen_modeSwitch);
    lv_img_set_src(ui_BrewScreen_volumetricButton, &ui_img_1424216268);
    lv_obj_set_width(ui_BrewScreen_volumetricButton, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_BrewScreen_volumetricButton, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_BrewScreen_volumetricButton, -29);
    lv_obj_set_y(ui_BrewScreen_volumetricButton, -81);
    lv_obj_set_align(ui_BrewScreen_volumetricButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_volumetricButton, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_BrewScreen_volumetricButton, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    ui_object_set_themeable_style_property(ui_BrewScreen_volumetricButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_volumetricButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_weightLabel = lv_label_create(ui_BrewScreen_modeSwitch);
    lv_obj_set_width(ui_BrewScreen_weightLabel, 90);
    lv_obj_set_height(ui_BrewScreen_weightLabel, 24);
    lv_obj_set_align(ui_BrewScreen_weightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_weightLabel, "0.0g");
    ui_object_set_themeable_style_property(ui_BrewScreen_weightLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_weightLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_BrewScreen_weightLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewScreen_weightLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_profileInfo = lv_obj_create(ui_BrewScreen_controlContainer);
    lv_obj_remove_style_all(ui_BrewScreen_profileInfo);
    lv_obj_set_width(ui_BrewScreen_profileInfo, 360);
    lv_obj_set_height(ui_BrewScreen_profileInfo, 120);
    lv_obj_set_x(ui_BrewScreen_profileInfo, 28);
    lv_obj_set_y(ui_BrewScreen_profileInfo, 62);
    lv_obj_set_align(ui_BrewScreen_profileInfo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrewScreen_profileInfo, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BrewScreen_profileInfo, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_profileInfo, LV_OBJ_FLAG_HIDDEN);                               /// Flags
    lv_obj_clear_flag(ui_BrewScreen_profileInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_pad_row(ui_BrewScreen_profileInfo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrewScreen_profileInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_Label1 = lv_label_create(ui_BrewScreen_profileInfo);
    lv_obj_set_width(ui_BrewScreen_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_BrewScreen_Label1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_BrewScreen_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_Label1, "Selected profile");
    ui_object_set_themeable_style_property(ui_BrewScreen_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_Label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_BrewScreen_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_Container3 = lv_obj_create(ui_BrewScreen_profileInfo);
    lv_obj_remove_style_all(ui_BrewScreen_Container3);
    lv_obj_set_width(ui_BrewScreen_Container3, 360);
    lv_obj_set_height(ui_BrewScreen_Container3, 40);
    lv_obj_set_align(ui_BrewScreen_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrewScreen_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BrewScreen_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrewScreen_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_pad_row(ui_BrewScreen_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrewScreen_Container3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_profileSelectBtn = lv_imgbtn_create(ui_BrewScreen_Container3);
    lv_imgbtn_set_src(ui_BrewScreen_profileSelectBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_332059803, NULL);
    lv_obj_set_height(ui_BrewScreen_profileSelectBtn, 40);
    lv_obj_set_width(ui_BrewScreen_profileSelectBtn, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_BrewScreen_profileSelectBtn, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_profileSelectBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_profileSelectBtn, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_profileName = lv_label_create(ui_BrewScreen_Container3);
    lv_obj_set_height(ui_BrewScreen_profileName, LV_SIZE_CONTENT); /// 1
    lv_obj_set_flex_grow(ui_BrewScreen_profileName, 1);
    lv_obj_set_x(ui_BrewScreen_profileName, -7);
    lv_obj_set_y(ui_BrewScreen_profileName, 21);
    lv_obj_set_align(ui_BrewScreen_profileName, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_BrewScreen_profileName, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_BrewScreen_profileName, "Cremina Lever");
    ui_object_set_themeable_style_property(ui_BrewScreen_profileName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_profileName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_BrewScreen_profileName, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_settingsButton = lv_imgbtn_create(ui_BrewScreen_Container3);
    lv_imgbtn_set_src(ui_BrewScreen_settingsButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_340148213, NULL);
    lv_obj_set_height(ui_BrewScreen_settingsButton, 40);
    lv_obj_set_width(ui_BrewScreen_settingsButton, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_BrewScreen_settingsButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_settingsButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_settingsButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_adjustments = lv_obj_create(ui_BrewScreen_controlContainer);
    lv_obj_remove_style_all(ui_BrewScreen_adjustments);
    lv_obj_set_width(ui_BrewScreen_adjustments, 360);
    lv_obj_set_height(ui_BrewScreen_adjustments, 120);
    lv_obj_set_x(ui_BrewScreen_adjustments, -1);
    lv_obj_set_y(ui_BrewScreen_adjustments, -14);
    lv_obj_set_align(ui_BrewScreen_adjustments, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrewScreen_adjustments, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BrewScreen_adjustments, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_BrewScreen_adjustments, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_pad_row(ui_BrewScreen_adjustments, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrewScreen_adjustments, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_tempContainer = lv_obj_create(ui_BrewScreen_adjustments);
    lv_obj_remove_style_all(ui_BrewScreen_tempContainer);
    lv_obj_set_width(ui_BrewScreen_tempContainer, 360);
    lv_obj_set_height(ui_BrewScreen_tempContainer, 50);
    lv_obj_set_align(ui_BrewScreen_tempContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrewScreen_tempContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_BrewScreen_targetTemp = lv_label_create(ui_BrewScreen_tempContainer);
    lv_obj_set_width(ui_BrewScreen_targetTemp, 90);
    lv_obj_set_height(ui_BrewScreen_targetTemp, 30);
    lv_obj_set_align(ui_BrewScreen_targetTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_targetTemp, "93°C");
    ui_object_set_themeable_style_property(ui_BrewScreen_targetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_targetTemp, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_BrewScreen_targetTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewScreen_targetTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_downTempButton = lv_imgbtn_create(ui_BrewScreen_tempContainer);
    lv_imgbtn_set_src(ui_BrewScreen_downTempButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_834125362, NULL);
    lv_obj_set_width(ui_BrewScreen_downTempButton, 40);
    lv_obj_set_height(ui_BrewScreen_downTempButton, 40);
    lv_obj_set_x(ui_BrewScreen_downTempButton, -80);
    lv_obj_set_y(ui_BrewScreen_downTempButton, 0);
    lv_obj_set_align(ui_BrewScreen_downTempButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_downTempButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_downTempButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_upTempButton = lv_imgbtn_create(ui_BrewScreen_tempContainer);
    lv_imgbtn_set_src(ui_BrewScreen_upTempButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_390988422, NULL);
    lv_obj_set_width(ui_BrewScreen_upTempButton, 40);
    lv_obj_set_height(ui_BrewScreen_upTempButton, 40);
    lv_obj_set_x(ui_BrewScreen_upTempButton, 80);
    lv_obj_set_y(ui_BrewScreen_upTempButton, 0);
    lv_obj_set_align(ui_BrewScreen_upTempButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_upTempButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_upTempButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_Image5 = lv_img_create(ui_BrewScreen_tempContainer);
    lv_img_set_src(ui_BrewScreen_Image5, &ui_img_1951499226);
    lv_obj_set_width(ui_BrewScreen_Image5, 40);
    lv_obj_set_height(ui_BrewScreen_Image5, 40);
    lv_obj_set_x(ui_BrewScreen_Image5, -140);
    lv_obj_set_y(ui_BrewScreen_Image5, 0);
    lv_obj_set_align(ui_BrewScreen_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_Image5, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_BrewScreen_Image5, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    ui_object_set_themeable_style_property(ui_BrewScreen_Image5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_Image5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_targetContainer = lv_obj_create(ui_BrewScreen_adjustments);
    lv_obj_remove_style_all(ui_BrewScreen_targetContainer);
    lv_obj_set_width(ui_BrewScreen_targetContainer, 360);
    lv_obj_set_height(ui_BrewScreen_targetContainer, 50);
    lv_obj_set_align(ui_BrewScreen_targetContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrewScreen_targetContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_BrewScreen_targetDuration = lv_label_create(ui_BrewScreen_targetContainer);
    lv_obj_set_width(ui_BrewScreen_targetDuration, 90);
    lv_obj_set_height(ui_BrewScreen_targetDuration, 30);
    lv_obj_set_align(ui_BrewScreen_targetDuration, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewScreen_targetDuration, "0:30");
    ui_object_set_themeable_style_property(ui_BrewScreen_targetDuration, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_targetDuration, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_BrewScreen_targetDuration, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewScreen_targetDuration, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewScreen_upDurationButton = lv_imgbtn_create(ui_BrewScreen_targetContainer);
    lv_imgbtn_set_src(ui_BrewScreen_upDurationButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_390988422, NULL);
    lv_obj_set_width(ui_BrewScreen_upDurationButton, 40);
    lv_obj_set_height(ui_BrewScreen_upDurationButton, 40);
    lv_obj_set_x(ui_BrewScreen_upDurationButton, 80);
    lv_obj_set_y(ui_BrewScreen_upDurationButton, 0);
    lv_obj_set_align(ui_BrewScreen_upDurationButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_upDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_upDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_downDurationButton = lv_imgbtn_create(ui_BrewScreen_targetContainer);
    lv_imgbtn_set_src(ui_BrewScreen_downDurationButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_834125362, NULL);
    lv_obj_set_width(ui_BrewScreen_downDurationButton, 40);
    lv_obj_set_height(ui_BrewScreen_downDurationButton, 40);
    lv_obj_set_x(ui_BrewScreen_downDurationButton, -80);
    lv_obj_set_y(ui_BrewScreen_downDurationButton, 0);
    lv_obj_set_align(ui_BrewScreen_downDurationButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_downDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR, _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_downDurationButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_Image4 = lv_img_create(ui_BrewScreen_targetContainer);
    lv_img_set_src(ui_BrewScreen_Image4, &ui_img_360122106);
    lv_obj_set_width(ui_BrewScreen_Image4, 40);
    lv_obj_set_height(ui_BrewScreen_Image4, 40);
    lv_obj_set_x(ui_BrewScreen_Image4, -140);
    lv_obj_set_y(ui_BrewScreen_Image4, 0);
    lv_obj_set_align(ui_BrewScreen_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrewScreen_Image4, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_BrewScreen_Image4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    ui_object_set_themeable_style_property(ui_BrewScreen_Image4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_Image4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_byTimeButton = lv_imgbtn_create(ui_BrewScreen_targetContainer);
    lv_imgbtn_set_src(ui_BrewScreen_byTimeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2074354459, NULL);
    lv_obj_set_width(ui_BrewScreen_byTimeButton, 40);
    lv_obj_set_height(ui_BrewScreen_byTimeButton, 40);
    lv_obj_set_x(ui_BrewScreen_byTimeButton, 140);
    lv_obj_set_y(ui_BrewScreen_byTimeButton, 0);
    lv_obj_set_align(ui_BrewScreen_byTimeButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_byTimeButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_byTimeButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_saveButton = lv_imgbtn_create(ui_BrewScreen_contentPanel4);
    lv_imgbtn_set_src(ui_BrewScreen_saveButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1594943393, NULL);
    lv_obj_set_width(ui_BrewScreen_saveButton, 30);
    lv_obj_set_height(ui_BrewScreen_saveButton, 30);
    lv_obj_set_x(ui_BrewScreen_saveButton, -70);
    lv_obj_set_y(ui_BrewScreen_saveButton, 130);
    lv_obj_set_align(ui_BrewScreen_saveButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_saveButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_saveButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_acceptButton = lv_imgbtn_create(ui_BrewScreen_contentPanel4);
    lv_imgbtn_set_src(ui_BrewScreen_acceptButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_631115820, NULL);
    lv_obj_set_width(ui_BrewScreen_acceptButton, 40);
    lv_obj_set_height(ui_BrewScreen_acceptButton, 40);
    lv_obj_set_x(ui_BrewScreen_acceptButton, 0);
    lv_obj_set_y(ui_BrewScreen_acceptButton, 130);
    lv_obj_set_align(ui_BrewScreen_acceptButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_acceptButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_acceptButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_BrewScreen_saveAsNewButton = lv_imgbtn_create(ui_BrewScreen_contentPanel4);
    lv_imgbtn_set_src(ui_BrewScreen_saveAsNewButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1464184441, NULL);
    lv_obj_set_width(ui_BrewScreen_saveAsNewButton, 30);
    lv_obj_set_height(ui_BrewScreen_saveAsNewButton, 30);
    lv_obj_set_x(ui_BrewScreen_saveAsNewButton, 70);
    lv_obj_set_y(ui_BrewScreen_saveAsNewButton, 130);
    lv_obj_set_align(ui_BrewScreen_saveAsNewButton, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BrewScreen_saveAsNewButton, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_BrewScreen_saveAsNewButton, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    lv_obj_add_event_cb(ui_BrewScreen_ImgButton5, ui_event_BrewScreen_ImgButton5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_startButton, ui_event_BrewScreen_startButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_modeSwitch, ui_event_BrewScreen_modeSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_profileSelectBtn, ui_event_BrewScreen_profileSelectBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_settingsButton, ui_event_BrewScreen_settingsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_downTempButton, ui_event_BrewScreen_downTempButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_upTempButton, ui_event_BrewScreen_upTempButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_upDurationButton, ui_event_BrewScreen_upDurationButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_downDurationButton, ui_event_BrewScreen_downDurationButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_byTimeButton, ui_event_BrewScreen_byTimeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_saveButton, ui_event_BrewScreen_saveButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_acceptButton, ui_event_BrewScreen_acceptButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen_saveAsNewButton, ui_event_BrewScreen_saveAsNewButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewScreen, ui_event_BrewScreen, LV_EVENT_ALL, NULL);
    uic_BrewScreen_dials_tempGauge = ui_comp_get_child(ui_BrewScreen_dials, UI_COMP_DIALS_TEMPGAUGE);
    uic_BrewScreen_dials_tempTarget = ui_comp_get_child(ui_BrewScreen_dials, UI_COMP_DIALS_TEMPTARGET);
    uic_BrewScreen_dials_pressureGauge = ui_comp_get_child(ui_BrewScreen_dials, UI_COMP_DIALS_PRESSUREGAUGE);
    uic_BrewScreen_dials_pressureTarget = ui_comp_get_child(ui_BrewScreen_dials, UI_COMP_DIALS_PRESSURETARGET);
    uic_BrewScreen_dials_pressureText = ui_comp_get_child(ui_BrewScreen_dials, UI_COMP_DIALS_PRESSURETEXT);
    uic_BrewScreen_dials_tempText = ui_comp_get_child(ui_BrewScreen_dials, UI_COMP_DIALS_TEMPTEXT);
}

void ui_BrewScreen_screen_destroy(void) {
    if (ui_BrewScreen)
        lv_obj_del(ui_BrewScreen);

    // NULL screen variables
    ui_BrewScreen = NULL;
    ui_BrewScreen_dials = NULL;
    uic_BrewScreen_dials_tempGauge = NULL;
    uic_BrewScreen_dials_tempTarget = NULL;
    uic_BrewScreen_dials_pressureGauge = NULL;
    uic_BrewScreen_dials_pressureTarget = NULL;
    uic_BrewScreen_dials_pressureText = NULL;
    uic_BrewScreen_dials_tempText = NULL;
    ui_BrewScreen_ImgButton5 = NULL;
    ui_BrewScreen_contentPanel4 = NULL;
    ui_BrewScreen_mainLabel3 = NULL;
    ui_BrewScreen_startButton = NULL;
    ui_BrewScreen_controlContainer = NULL;
    ui_BrewScreen_modeSwitch = NULL;
    ui_BrewScreen_volumetricButton = NULL;
    ui_BrewScreen_weightLabel = NULL;
    ui_BrewScreen_profileInfo = NULL;
    ui_BrewScreen_Label1 = NULL;
    ui_BrewScreen_Container3 = NULL;
    ui_BrewScreen_profileSelectBtn = NULL;
    ui_BrewScreen_profileName = NULL;
    ui_BrewScreen_settingsButton = NULL;
    ui_BrewScreen_adjustments = NULL;
    ui_BrewScreen_tempContainer = NULL;
    ui_BrewScreen_targetTemp = NULL;
    ui_BrewScreen_downTempButton = NULL;
    ui_BrewScreen_upTempButton = NULL;
    ui_BrewScreen_Image5 = NULL;
    ui_BrewScreen_targetContainer = NULL;
    ui_BrewScreen_targetDuration = NULL;
    ui_BrewScreen_upDurationButton = NULL;
    ui_BrewScreen_downDurationButton = NULL;
    ui_BrewScreen_Image4 = NULL;
    ui_BrewScreen_byTimeButton = NULL;
    ui_BrewScreen_saveButton = NULL;
    ui_BrewScreen_acceptButton = NULL;
    ui_BrewScreen_saveAsNewButton = NULL;
}
