// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_BREWSCREEN_H
#define UI_BREWSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BrewScreen
extern void ui_BrewScreen_screen_init(void);
extern void ui_BrewScreen_screen_destroy(void);
extern void ui_event_BrewScreen(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen;
extern lv_obj_t *ui_BrewScreen_dials;
extern void ui_event_BrewScreen_ImgButton5(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_ImgButton5;
extern lv_obj_t *ui_BrewScreen_contentPanel4;
extern lv_obj_t *ui_BrewScreen_mainLabel3;
extern void ui_event_BrewScreen_startButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_startButton;
extern lv_obj_t *ui_BrewScreen_controlContainer;
extern void ui_event_BrewScreen_modeSwitch(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_modeSwitch;
extern lv_obj_t *ui_BrewScreen_volumetricButton;
extern lv_obj_t *ui_BrewScreen_weightLabel;
extern lv_obj_t *ui_BrewScreen_profileInfo;
extern lv_obj_t *ui_BrewScreen_Label1;
extern lv_obj_t *ui_BrewScreen_Container3;
extern void ui_event_BrewScreen_profileSelectBtn(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_profileSelectBtn;
extern lv_obj_t *ui_BrewScreen_profileName;
extern void ui_event_BrewScreen_settingsButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_settingsButton;
extern lv_obj_t *ui_BrewScreen_adjustments;
extern lv_obj_t *ui_BrewScreen_tempContainer;
extern lv_obj_t *ui_BrewScreen_targetTemp;
extern void ui_event_BrewScreen_downTempButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_downTempButton;
extern void ui_event_BrewScreen_upTempButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_upTempButton;
extern lv_obj_t *ui_BrewScreen_Image5;
extern lv_obj_t *ui_BrewScreen_targetContainer;
extern lv_obj_t *ui_BrewScreen_targetDuration;
extern void ui_event_BrewScreen_upDurationButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_upDurationButton;
extern void ui_event_BrewScreen_downDurationButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_downDurationButton;
extern lv_obj_t *ui_BrewScreen_Image4;
extern void ui_event_BrewScreen_byTimeButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_byTimeButton;
extern void ui_event_BrewScreen_saveButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_saveButton;
extern void ui_event_BrewScreen_acceptButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_acceptButton;
extern void ui_event_BrewScreen_saveAsNewButton(lv_event_t *e);
extern lv_obj_t *ui_BrewScreen_saveAsNewButton;
// CUSTOM VARIABLES
extern lv_obj_t *uic_BrewScreen_dials_tempGauge;
extern lv_obj_t *uic_BrewScreen_dials_tempTarget;
extern lv_obj_t *uic_BrewScreen_dials_pressureGauge;
extern lv_obj_t *uic_BrewScreen_dials_pressureTarget;
extern lv_obj_t *uic_BrewScreen_dials_pressureText;
extern lv_obj_t *uic_BrewScreen_dials_tempText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
