// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_STANDBYSCREEN_H
#define UI_STANDBYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StandbyScreen
extern void ui_StandbyScreen_screen_init(void);
extern void ui_StandbyScreen_screen_destroy(void);
extern void ui_event_StandbyScreen(lv_event_t *e);
extern lv_obj_t *ui_StandbyScreen;
extern lv_obj_t *ui_StandbyScreen_logo;
extern lv_obj_t *ui_StandbyScreen_time;
extern lv_obj_t *ui_StandbyScreen_statusContainer;
extern lv_obj_t *ui_StandbyScreen_wifiIcon;
extern lv_obj_t *ui_StandbyScreen_bluetoothIcon;
extern lv_obj_t *ui_StandbyScreen_updateIcon;
extern lv_obj_t *ui_StandbyScreen_touchIcon;
extern lv_obj_t *ui_StandbyScreen_mainLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
