// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: GaggiMate

#include "../ui.h"

lv_obj_t *ui_StandbyScreen = NULL;
lv_obj_t *ui_StandbyScreen_logo = NULL;
lv_obj_t *ui_StandbyScreen_time = NULL;
lv_obj_t *ui_StandbyScreen_statusContainer = NULL;
lv_obj_t *ui_StandbyScreen_wifiIcon = NULL;
lv_obj_t *ui_StandbyScreen_bluetoothIcon = NULL;
lv_obj_t *ui_StandbyScreen_updateIcon = NULL;
lv_obj_t *ui_StandbyScreen_touchIcon = NULL;
lv_obj_t *ui_StandbyScreen_mainLabel = NULL;
// event funtions
void ui_event_StandbyScreen(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_CLICKED) {
        onWakeup(e);
    }
}

// build funtions

void ui_StandbyScreen_screen_init(void) {
    ui_StandbyScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StandbyScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_event_cb(ui_StandbyScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, ui_StandbyScreen_screen_destroy);
    ui_object_set_themeable_style_property(ui_StandbyScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_StandbyScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Dark);

    ui_StandbyScreen_logo = lv_img_create(ui_StandbyScreen);
    lv_img_set_src(ui_StandbyScreen_logo, &ui_img_logo_png);
    lv_obj_set_width(ui_StandbyScreen_logo, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_StandbyScreen_logo, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_StandbyScreen_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_logo, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_StandbyScreen_logo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_StandbyScreen_logo, 210);
    ui_object_set_themeable_style_property(ui_StandbyScreen_logo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_StandbyScreen_logo, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_StandbyScreen_time = lv_label_create(ui_StandbyScreen);
    lv_obj_set_width(ui_StandbyScreen_time, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_StandbyScreen_time, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_StandbyScreen_time, 0);
    lv_obj_set_y(ui_StandbyScreen_time, -150);
    lv_obj_set_align(ui_StandbyScreen_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StandbyScreen_time, "0:00");
    lv_obj_add_flag(ui_StandbyScreen_time, LV_OBJ_FLAG_HIDDEN); /// Flags
    ui_object_set_themeable_style_property(ui_StandbyScreen_time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_StandbyScreen_time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_align(ui_StandbyScreen_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StandbyScreen_time, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StandbyScreen_statusContainer = lv_obj_create(ui_StandbyScreen);
    lv_obj_remove_style_all(ui_StandbyScreen_statusContainer);
    lv_obj_set_width(ui_StandbyScreen_statusContainer, 300);
    lv_obj_set_height(ui_StandbyScreen_statusContainer, 20);
    lv_obj_set_x(ui_StandbyScreen_statusContainer, 0);
    lv_obj_set_y(ui_StandbyScreen_statusContainer, -210);
    lv_obj_set_align(ui_StandbyScreen_statusContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StandbyScreen_statusContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_StandbyScreen_statusContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_statusContainer, LV_OBJ_FLAG_HIDDEN);                               /// Flags
    lv_obj_clear_flag(ui_StandbyScreen_statusContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_StandbyScreen_wifiIcon = lv_img_create(ui_StandbyScreen_statusContainer);
    lv_img_set_src(ui_StandbyScreen_wifiIcon, &ui_img_364513079);
    lv_obj_set_width(ui_StandbyScreen_wifiIcon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_StandbyScreen_wifiIcon, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_StandbyScreen_wifiIcon, 20);
    lv_obj_set_y(ui_StandbyScreen_wifiIcon, -210);
    lv_obj_set_align(ui_StandbyScreen_wifiIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_wifiIcon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_StandbyScreen_wifiIcon, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    ui_object_set_themeable_style_property(ui_StandbyScreen_wifiIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_StandbyScreen_wifiIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_border_width(ui_StandbyScreen_wifiIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_StandbyScreen_wifiIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_StandbyScreen_wifiIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_StandbyScreen_bluetoothIcon = lv_img_create(ui_StandbyScreen_statusContainer);
    lv_img_set_src(ui_StandbyScreen_bluetoothIcon, &ui_img_1091371356);
    lv_obj_set_width(ui_StandbyScreen_bluetoothIcon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_StandbyScreen_bluetoothIcon, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_StandbyScreen_bluetoothIcon, -20);
    lv_obj_set_y(ui_StandbyScreen_bluetoothIcon, -210);
    lv_obj_set_align(ui_StandbyScreen_bluetoothIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_bluetoothIcon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_StandbyScreen_bluetoothIcon, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    ui_object_set_themeable_style_property(ui_StandbyScreen_bluetoothIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_StandbyScreen_bluetoothIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_border_width(ui_StandbyScreen_bluetoothIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_StandbyScreen_bluetoothIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_StandbyScreen_bluetoothIcon, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_IMG_RECOLOR_OPA, _ui_theme_alpha_NiceWhite);

    ui_StandbyScreen_updateIcon = lv_img_create(ui_StandbyScreen_statusContainer);
    lv_img_set_src(ui_StandbyScreen_updateIcon, &ui_img_1765671371);
    lv_obj_set_width(ui_StandbyScreen_updateIcon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_StandbyScreen_updateIcon, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_StandbyScreen_updateIcon, -20);
    lv_obj_set_y(ui_StandbyScreen_updateIcon, -210);
    lv_obj_set_align(ui_StandbyScreen_updateIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_updateIcon, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_StandbyScreen_updateIcon, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    ui_object_set_themeable_style_property(ui_StandbyScreen_updateIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Dark);
    ui_object_set_themeable_style_property(ui_StandbyScreen_updateIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Dark);
    lv_obj_set_style_border_width(ui_StandbyScreen_updateIcon, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_StandbyScreen_updateIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_StandbyScreen_updateIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_StandbyScreen_touchIcon = lv_img_create(ui_StandbyScreen);
    lv_img_set_src(ui_StandbyScreen_touchIcon, &ui_img_1732953241);
    lv_obj_set_width(ui_StandbyScreen_touchIcon, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_StandbyScreen_touchIcon, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_StandbyScreen_touchIcon, 0);
    lv_obj_set_y(ui_StandbyScreen_touchIcon, 150);
    lv_obj_set_align(ui_StandbyScreen_touchIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StandbyScreen_touchIcon, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_StandbyScreen_touchIcon, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
    lv_img_set_zoom(ui_StandbyScreen_touchIcon, 210);
    ui_object_set_themeable_style_property(ui_StandbyScreen_touchIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_StandbyScreen_touchIcon, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMG_RECOLOR_OPA,
                                           _ui_theme_alpha_NiceWhite);

    ui_StandbyScreen_mainLabel = lv_label_create(ui_StandbyScreen);
    lv_obj_set_width(ui_StandbyScreen_mainLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_StandbyScreen_mainLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_StandbyScreen_mainLabel, 0);
    lv_obj_set_y(ui_StandbyScreen_mainLabel, 150);
    lv_obj_set_align(ui_StandbyScreen_mainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StandbyScreen_mainLabel, "Starting...");
    ui_object_set_themeable_style_property(ui_StandbyScreen_mainLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_NiceWhite);
    ui_object_set_themeable_style_property(ui_StandbyScreen_mainLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_NiceWhite);
    lv_obj_set_style_text_font(ui_StandbyScreen_mainLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_StandbyScreen, ui_event_StandbyScreen, LV_EVENT_ALL, NULL);
}

void ui_StandbyScreen_screen_destroy(void) {
    if (ui_StandbyScreen)
        lv_obj_del(ui_StandbyScreen);

    // NULL screen variables
    ui_StandbyScreen = NULL;
    ui_StandbyScreen_logo = NULL;
    ui_StandbyScreen_time = NULL;
    ui_StandbyScreen_statusContainer = NULL;
    ui_StandbyScreen_wifiIcon = NULL;
    ui_StandbyScreen_bluetoothIcon = NULL;
    ui_StandbyScreen_updateIcon = NULL;
    ui_StandbyScreen_touchIcon = NULL;
    ui_StandbyScreen_mainLabel = NULL;
}
